// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from './types';



const SUPABASE_URL = "https://sbfffeioctstcieomqiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZmZmZWlvY3RzdGNpZW9tcWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjIyMTIsImV4cCI6MjA2NDMzODIxMn0.zzdUjkdTj7eE44R7siZpcMRLUwPINfVDMSazKjaRyOk";



export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

